config/routes.rb
RoomSchedule::Application.routes.draw do

  root to: "schedule#index"

  get    "/new"         => "schedule#new",     as: "new"
  post   "/create"      => "schedule#create",  as: "create"
  delete "/destroy/:id" => "schedule#destroy", as: "destroy"

end

app/controllers/schedule_controller.rb
# coding: utf-8
require "concerns/user_status"
require "concerns/facility_status"
include UserStatus
include FacilityStatus

class ScheduleController < ApplicationController

  def index
    @users        = get_users(UserStatus.all)
    @facilities   = get_facilities(FacilityStatus.all)
    @all_bookings = get_bookings

    if params[:booking_search_form]
      @search_form     = BookingSearchForm.new(params[:booking_search_form])
      @result_bookings = @search_form.result_bookings
    else
      @search_form     = BookingSearchForm.new
      @result_bookings = @all_bookings
    end
  end

  def new
    @users      = get_users(UserStatus::ACTIVE)
    @facilities = get_facilities(FacilityStatus::ACTIVE)

    @booking = Booking.new
  end

  def create
    @users      = get_users(UserStatus::ACTIVE)
    @facilities = get_facilities(FacilityStatus::ACTIVE)

    @booking = Booking.new(params[:booking])
    @booking[:start_time] = @booking.start_time
    @booking[:end_time]   = @booking.end_time

    if @booking.save
      redirect_to :root, notice: "予約の登録が完了しました。"
    else
      render "new"
    end
  end

  def destroy
    begin
      @booking = set_booking
      @booking.destroy
      render json: {booking: @booking, notice: "予約を削除しました。"}
      # redirect_to :root, notice: "予約を削除しました。"
    rescue ActiveRecord::RecordNotFound => e
      render json: {alert: "指定の予約は見つかりませんでした。"}
      # redirect_to :root, alert: "指定の予約は見つかりませんでした。"
    end
  end

  private

  def get_users(status)
    users = User.order("family_kana")
    if status.present?
      users = users.where('status = ?', status)
    end
    return users
  end

  def get_facilities(status)
    facilities = Facility.order("id")
    if status.present?
      facilities = facilities.where('status = ?', status)
    end
    return facilities
  end

  def get_bookings
    bookings = Booking.order("start_time DESC")
  end

  def set_booking
    booking = Booking.find(params[:id])
  end

end

app/helpers/schedule_helper.rb
# coding: utf-8
module ScheduleHelper

  #
  # selectのoptions：年
  #
  def select_year_options(options = {})
    select_year_options = []

    time_now = Time.zone.now
    start_year = time_now.year.to_i
    end_year   = start_year + (options[:over_year] ||= 10).to_i

    (start_year).upto(end_year) do |year|
      select_year_options << ["#{year} #{options[:unit]}", year]
    end
    return select_year_options
  end

  #
  # selectのoptions：月
  #
  def select_month_options(options = {})
    select_month_options = []
    (1).upto(12) do |month|
      select_month_options << ["#{month} #{options[:unit]}", month]
    end
    return select_month_options
  end

  #
  # selectのoptions：日
  #
  def select_day_options(options = {})
    select_day_options = []
    (1).upto(31) do |day|
      select_day_options << ["#{day} #{options[:unit]}", day]
    end
    return select_day_options
  end

  #
  # selectのoptions：時
  #
  def select_hour_options(options = {})
    select_hour_options = []
    (0).upto(23) do |hour|
      select_hour_options << ["#{hour} #{options[:unit]}", hour]
    end
    return select_hour_options
  end

  #
  # selectのoptions：分
  #
  def select_min_options(options = {})
    select_min_options = []
    step = options[:step] ? options[:step].to_i : 1
    (0).step(59, step) do |min|
      min = "%02d" % min
      select_min_options << ["#{min} #{options[:unit]}", min]
    end
    return select_min_options
  end

  #
  # selectのoptions：登録者
  #
  def select_user_options(users = {})
    select_user_options = []

    if users.present? && users.size > 0
      users.each do |u|
        user_name  = ""
        user_name += u[:family_name]
        user_name += " #{u[:first_name]}"
        if(u[:family_kana].present? || u[:first_kana].present?)
          user_name += "（"
          user_name += "#{u[:family_kana].to_hiragana}"
          user_name += " #{u[:first_kana].to_hiragana}"
          user_name += "）"
        end
        select_user_options << [user_name, u.id]
      end
    end
    return select_user_options
  end

  #
  # selectのoptions：会議室
  #
  def select_facility_options(facilities = {})
    select_facility_options = []

    if facilities.present? && facilities.size > 0
      facilities.each do |f|
        facility_name = f[:name]
        if f[:sub_name].present?
          facility_name += "：#{f[:sub_name]}"
        end
        select_facility_options << [facility_name, f.id]
      end
    end
    return select_facility_options
  end

  #
  # 会議室名の成型
  #
  def facility_name(facility = {})
    facility_name = facility[:name]
    if facility[:sub_name].present?
      facility_name += "：#{facility[:sub_name]}"
    end
    return facility_name
  end

end

app/views/schedule/index.html.erb
<article class="l-contents">
  <div id="js-flash-messages">
    <%= render "/shared/flash", flash: flash %>
    <%= render "/shared/errors", obj: @search_form %>
  </div>

  <h2 class="c-heading2">
    予約検索
  </h2>

  <%= form_for(@search_form, url: :root, html: {method: :get}) do |f| %>
    <table class="c-table search-table">
      <tbody>
        <tr>
          <th>
            <%= f.label :date_year %>
          </th>
          <td>
            <%= f.select :date_year, options_for_select(select_year_options(unit: "年", over_year: 5), @search_form.try(:date_year)) %>
            <%= f.select :date_month, options_for_select(select_month_options(unit: "月"), @search_form.try(:date_month)) %>
            <%= f.select :date_day, options_for_select(select_day_options(unit: "日"), @search_form.try(:date_day)) %>
            <span class="form-error"></span>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :title %>
          </th>
          <td>
            <%= f.text_field :title, {maxlength: 50, class: "c-textfield"} %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :user_id %>
          </th>
          <td>
            <%= f.select :user_id, options_for_select(select_user_options(@users), @search_form.try(:user_id)), {include_blank: "-----"} %>
          </td>
        </tr>
        <tr>
          <th>
            <%= f.label :facility_id %>
          </th>
          <td>
            <%= f.select :facility_id, options_for_select(select_facility_options(@facilities), @search_form.try(:facility_id)), {include_blank: "-----"} %>
          </td>
        </tr>
        <tr>
          <td colspan="2" class="submit-th">
            <%= f.submit "検索する", {class: "c-btn c-btn--primary submit-th__btn"} %>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>

  <% if @all_bookings && @all_bookings.size > 0 %>
    <% if @result_bookings && @result_bookings.size > 0 %>

      <p class="result-count">
        <% if @result_bookings != @all_bookings %>
          <b class="result-count__num js-booking-count"><%= @result_bookings.size %></b> 件
          / 全 <b class="js-booking-count"><%= @all_bookings.size %></b> 件
        <% else %>
          全 <b class="result-count__num js-booking-count"><%= @all_bookings.size %></b> 件
        <% end %>
      </p>

      <% @result_bookings.each do |booking| %>
        <table class="result-table" id="js-booking-<%= booking.id %>">
          <tbody>
            <tr>
              <th>
                日時
              </th>
              <td>
                <%= booking[:start_time].strftime("%Y/%m/%d %H:%M") %>
                ～
                <%= booking[:end_time].strftime("%Y/%m/%d %H:%M") %>
              </td>
              <td rowspan="5" class="result-table__form">
                <%= link_to "削除", destroy_path(id: booking.id) , confirm: "本当に削除しますか？", method: :delete, remote: true %>
              </td>
            </tr>
            <tr>
              <th>
                タイトル
              </th>
              <td>
                <%= booking.title.present? ? booking.title : content_tag(:span, "無題", class: "c-text-quiet") %>
              </td>
            </tr>
            <tr>
              <th>
                会議室
              </th>
              <td<% if booking.facility.status != FacilityStatus::ACTIVE %> class="status-inactive"<% end %>>
                <%= facility_name(booking.facility) %>
              </td>
            </tr>
            <tr>
              <th>
                登録者
              </th>
              <td<% if booking.user.status != UserStatus::ACTIVE %> class="status-inactive"<% end %>>
                <%= booking.user.family_name %>
                <%= booking.user.first_name %>
                <span class="user-name-kana">
                （
                  <%= booking.user.family_kana.to_hiragana %>
                  <%= booking.user.first_kana.to_hiragana %>
                  ）
                </span>
              </td>
            </tr>
            <tr>
              <th>
                メモ
              </th>
              <td>
                <%= booking.memo.present? ? url_to_link(hbr(booking.memo)).html_safe : content_tag(:span, "-", class: "c-text-quiet") %>
              </td>
            </tr>
          </tbody>
        </table>
      <% end %>

    <% else %>
      <div class="c-alert is-primary">
        <p class="c-alert__title">
          指定された条件での予約は見つかりませんでした。
        </p>
        <p class="anime-oops">
          <%= image_tag("/images/sushiyuki/sushiyuki_69.png", size: "150x150", alt: "", class: "anime-oops__img")  %>
          <%= image_tag("/images/sushiyuki/sushiyuki_70.png", size: "150x150", alt: "", class: "anime-oops__img")  %>
        </pff
      </div>
    <% end %>
  <% else %>
    <div class="c-alert">
      <p class="c-alert__title">
        予約はありません。
      </p>
      <p><%= image_tag("/images/sushiyuki/sushiyuki_39.png", size: "150x150", alt: "")  %></p>
    </div>
  <% end %>

</article>

app/views/schedule/new.html.erb
<article class="l-contents">

  <%= render "/shared/flash", flash: flash %>
  <%= render "/shared/errors", obj: @booking %>

  <h2 class="c-heading2">
    予約登録
  </h2>

  <%= form_for(@booking, url: "create", html: {method: :post}) do |f| %>
    <table class="c-table form-table">
      <tbody>
        <tr>
          <th class="form-table__th">
            <b class="form-table__label form-table__label--required">必須</b>
            日時
          </th>
          <td>
            <div class="form-table__line">
              <%= f.label :start_time, "開始：" %>
              <%= f.select :start_year, options_for_select(select_year_options(unit: "年", over_year: 5), @booking.try(:start_year)) %>
              <%= f.select :start_month, options_for_select(select_month_options(unit: "月"), @booking.try(:start_month)) %>
              <%= f.select :start_day, options_for_select(select_day_options(unit: "日"), @booking.try(:start_day)) %>
              <%= f.select :start_hour, options_for_select(select_hour_options(unit: "時"), @booking.try(:start_hour)), {include_blank: "-- 時"} %>
              <%= f.select :start_min, options_for_select(select_min_options(unit: "分", step: 15), @booking.try(:start_min)), {include_blank: "-- 分"} %>
              <span class="form-error"></span>
            </div>
            <div class="form-table__line">
              <%= f.label :end_time, "終了：" %>
              <%= f.select :end_year, options_for_select(select_year_options(unit: "年", over_year: 5), @booking.try(:end_year)) %>
              <%= f.select :end_month, options_for_select(select_month_options(unit: "月"), @booking.try(:end_month)) %>
              <%= f.select :end_day, options_for_select(select_day_options(unit: "日"), @booking.try(:end_day)) %>
              <%= f.select :end_hour, options_for_select(select_hour_options(unit: "時"), @booking.try(:end_hour)), {include_blank: "-- 時"} %>
              <%= f.select :end_min, options_for_select(select_min_options(unit: "分", step: 15), @booking.try(:end_min)), {include_blank: "-- 分"} %>
              <span class="form-error"></span>
            </div>
          </td>
        </tr>
        <tr>
          <th class="form-table__th">
            <span class="form-table__label">任意</span>
            <%= f.label :title %>
            <small class="form-table__limit">50文字以内</small>
          </th>
          <td>
            <%= f.text_field :title, {maxlength: 50, placeholder: "無題", class: "c-textfield"} %>
            <span class="form-error"></span>
          </td>
        </tr>
        <tr>
          <th class="form-table__th">
            <b class="form-table__label form-table__label--required">必須</b>
            <%= f.label :user_id %>
          </th>
          <td>
            <%= f.select :user_id, options_for_select(select_user_options(@users), @booking.try(:user_id)) %>
            <span class="form-error"></span>
          </td>
        </tr>
        <tr>
          <th class="form-table__th">
            <b class="form-table__label form-table__label--required">必須</b>
            <%= f.label :facility_id %>
          </th>
          <td>
            <%= f.select :facility_id, options_for_select(select_facility_options(@facilities), @booking.try(:facility_id)) %>
            <span class="form-error"></span>
          </td>
        </tr>
        <tr>
          <th class="form-table__th">
            <span class="form-table__label">任意</span>
            <%= f.label :memo %>
            <small class="form-table__limit">100文字以内</small>
          </th>
          <td>
            <%= f.text_area :memo, {maxlength: 100, class: "c-textfield c-textfield--textarea"} %>
            <span class="form-error"></span>
          </td>
        </tr>
        <tr>
          <td colspan="2" class="submit-th">
            <%= f.submit "登録する", {class: "c-btn c-btn--success submit-th__btn"} %>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>

</article>